### ISSUE TITLE
Issues with Swift 1.2

### ISSUE THREAD

**Issue by bennichols** [brynbellomy/SwiftBitmask#1]
@brynbellomy  Hi there, love the idea of the library, but I'm having trouble getting it to compile with Swift 1.2. There seems to be issues in SwiftBitmask, Funky and Llama. I thought I had most of them fixed, but my compiler is now seg faulting and I have no idea what's going on.

**Comment by brynbellomy** [comment]
Hey — which version of LlamaKit are you using?  I have SwiftBitmask + Funky + Llama working on a Swift 1.2 project right now, but I might need to push some changes up here to get that working.  Let me know and I'll take a look in just a bit.

**Comment by bennichols** [comment]
@brynbellomy I'm using the version that's in the SwiftBitmask repo under Pods.

**Comment by brynbellomy** [comment]
@bennichols I just pushed version 0.2.2 of Funky and 0.1.0 of SwiftBitmask (git tags + cocoapods) — they pass all tests and generate no warnings.  Would you mind giving the new version a shot?  Funky no longer depends on LlamaKit, which has been causing headaches since Swift is changing so much still.

**Comment by zenvendof** [comment]
"Class _SwiftNativeNSEnumeratorBase is implemented in both blah blah, one is undefined" (Seems like swiftcore is linked in the framework?) was showing up with the Pod deployment....any idea why?

**Comment by brynbellomy** [comment]
@zenvendof Interesting, and thanks for the heads up.  I'm going to start looking into this.  I haven't been able to replicate the problem, though, and I'm using SwiftBitmask on a number of projects.  Do you have a repo or zip of the project where you're seeing this issue?

**Comment by brynbellomy** [comment]
@zenvendof Are you on Xcode 6.3.1 or 6.4 beta 2?  Or something else entirely?

**Comment by zenvendof** [comment]
@brynbellomy Thanks for the quick turn around :-), created the follow to assist trouble shooting:
1. Start Xcode 6.3.1
2. Create a OS X Console Project
3. Exit
4. Go to project folder, create Podfile (Cocoapod 0.37)
5. Pod install
6. Completed, green light
7. Start new project workspace
8. Build and run
9. The following occurs:

![bitmask doh](https://cloud.githubusercontent.com/assets/902416/7486576/bc0a42f2-f3d9-11e4-94f7-a63279e54c5d.png)
1. I think some how the included Swift runtime headers are made public. 
2. Project uploaded to Github: (https://github.com/zenvendof/SwiftBitmaskTest)

Let me know, would have saved me loads of boiler plate code for NS_OPTIONS styled structs!  For now I hand coded them (It was horrible!) but I get almost a 40% speed bump as I create a bunch of objects (over 20000) at start time and it was using Set to compare options (superset).....  testing a UINT is easier :-D

Hope we got fix it, awesome work!  Cheers

**Comment by brynbellomy** [comment]
@zenvendof I cloned your SwiftBitmaskTest repo, added the following Podfile:

``` ruby
use_frameworks!
pod 'SwiftBitmask'
```

... did `pod install`, opened the xcworkspace file, built, and ran the project... didn't see any errors like the one you sent a screenshot of.  Do you have the `use_frameworks!` line in your Podfile?  (it's a fairly new requirement for Swift pods)

The other thing that occurred to me is that if you're having linker/shared library trouble, but you're using Cocoapods, the problem is probably in Xcode or Cocoapods (or maybe the Podfile like I mentioned above).  The code in the SwiftBitmask library itself shouldn't be causing duplicate definition errors.  Very strange.

Oh, last thing — I've tinkered around with making Swift command line programs a little bit, but only enough to know that it's not always straightforward.  I think you have to set the project up a little bit differently to get it to work with Swift, but I don't know what the current state of affairs is (i.e., since Swift 1.2 was released).

Anyway, let me know if that Podfile fix works.  Otherwise, maybe just make an Xcode target manually and drag the source files in?  You could maybe try [Carthage](https://github.com/Carthage/Carthage) too ... I've used it occasionally when Cocoapods won't cooperate.

**Comment by brynbellomy** [comment]
Going to close this for now due to inactivity, but if you continue to have problems feel free to reopen.
